# Generated by Django 2.2.16 on 2022-07-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220710_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/image/', verbose_name='Картинка'),
        ),
    ]
